### ISSUE TITLE
Keymesh 2.3 support for Blender 4.1

### ISSUE THREAD

**Issue by Dereuz24** [nickberckley/keymesh#36]
Hi there,

Is it really not possible to install 2.3 on Blender 4.1? For a lot of reasons (including eevee legacy) many of us are still going to be stuck working with 4.1 and these features on Keymesh are just too important in terms of productivity and workflow to not be able to use them in current pipelines

**Comment by nickberckley** [comment]
Hey,

Unfortunately, since add-ons started using extensions schema in 4.2 we had to make hard splits between versions before and after to keep development easier (some features of Keymesh 2.3 aren't supported in 4.2, but it's installable). Supporting both pre-4.2 and post-4.2 is possible, but the add-on hasn't been tested in previous versions and I can't guarantee that it will work.

I can modify .zip file little to make it installable on 4.1, but I can't guarantee it's stability and I won't be fixing bugs for it if they're specific for that version.

**Comment by Dereuz24** [comment]
Hey there. I understand, that would be very helpful thank you

Even if it's unstable or some features are limited it would allow some flexibility until  migrating to 4.2 becomes more viable. If any problem arises the users could use 4.2 to complete keymesh animation and then go back to 4.1 and merge the keymesh objects back into their pipelines, but with the previous version of the addon that  becomes a lot more difficult to do

**Comment by nickberckley** [comment]
This is the file for 4.1 and earlier versions. If you make something cool with it share with us.

[keymesh.zip](https://github.com/user-attachments/files/18230349/keymesh.zip)

**Comment by Dereuz24** [comment]
> This is the file for 4.1 and earlier versions. If you make something cool with it share with us.
> 
> [keymesh.zip](https://github.com/user-attachments/files/18230349/keymesh.zip)

Thank you very much! It works!
